### ISSUE TITLE
Spikolodon spikes, pillkeeper, and clara's bell

### ISSUE THREAD

**Issue by horrible-little-slime** [loathers/chrono-collector#28]

**Comment by docrostov** [comment]
see my caveman issue (#45) for a dumb-ish use of these.

smart use is just use them all in the first floor for twitching time capsules. they're going to be cheap for a while but solid shifting time weirdness is never going to be <100k i think, and that means each of those NCs is ~5 chroners + 10k, which actually whips ass and is good and not bad.
